
[mobs]
	show_level = true
	blacklist = []
	exp_bonus_per_level = 0.1
	whitelist = []

[attributes]
	movement_speed_per_level = 0.001
	flying_speed_per_level = 0.001
	attack_damage_per_level = 0.1
	armor_per_level = 0.1
	health_per_level = 0.1

