
[general]
	#Should the (regular) charcoal blocks be enabled?
	charcoalBlockEnabled = true
	#Fuel value of sugarcane charcoal
	#Range: > 1
	sugarcaneCharcoalFuelValue = 600
	#Fuel value of carrot charcoal
	#Range: > 1
	carrotCharcoalFuelValue = 600
	#Fuel value of potato charcoal
	#Range: > 1
	potatoCharcoalFuelValue = 800
	#Fuel value of beet charcoal
	#Range: > 1
	beetCharcoalFuelValue = 600
	#Fuel value of apple charcoal
	#Range: > 1
	appleCharcoalFuelValue = 600
	#Fuel value of chorus charcoal
	#Range: > 1
	chorusCharcoalFuelValue = 1200
	#Fuel value of egg charcoal
	#Range: > 1
	eggCharcoalFuelValue = 800
	#Fuel value of bread charcoal
	#Range: > 1
	breadCharcoalFuelValue = 1200
	#Fuel value of melon charcoal
	#Range: > 1
	melonCharcoalFuelValue = 600

